//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveV3._0.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveV3._0.Resources.Lang.ES", typeof(ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancelar.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Añadir.
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crea la salvaguardia.
        /// </summary>
        internal static string CreateSaveButton {
            get {
                return ResourceManager.GetString("CreateSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suprimir.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modificar.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modificar.
        /// </summary>
        internal static string EditSaveButton {
            get {
                return ResourceManager.GetString("EditSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ejecutar.
        /// </summary>
        internal static string ExecuteButton {
            get {
                return ResourceManager.GetString("ExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre.
        /// </summary>
        internal static string HeaderGridViewName {
            get {
                return ResourceManager.GetString("HeaderGridViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string HeaderGridViewSource {
            get {
                return ResourceManager.GetString("HeaderGridViewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destino.
        /// </summary>
        internal static string HeaderGridViewTarget {
            get {
                return ResourceManager.GetString("HeaderGridViewTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tipo.
        /// </summary>
        internal static string HeaderGridViewType {
            get {
                return ResourceManager.GetString("HeaderGridViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histórico.
        /// </summary>
        internal static string HeaderItemLog {
            get {
                return ResourceManager.GetString("HeaderItemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parámetros.
        /// </summary>
        internal static string HeaderItemParam {
            get {
                return ResourceManager.GetString("HeaderItemParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salvaguardia.
        /// </summary>
        internal static string HeaderItemSave {
            get {
                return ResourceManager.GetString("HeaderItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cambiar de idioma.
        /// </summary>
        internal static string LabelChangeLang {
            get {
                return ResourceManager.GetString("LabelChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seleccione los archivos que desea encriptar.
        /// </summary>
        internal static string LabelCryptExten {
            get {
                return ResourceManager.GetString("LabelCryptExten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elija el formato del archivo de registro.
        /// </summary>
        internal static string LabelFileFormat {
            get {
                return ResourceManager.GetString("LabelFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elegir extensiones prioritarias.
        /// </summary>
        internal static string LabelFilePriority {
            get {
                return ResourceManager.GetString("LabelFilePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elija la ruta para los archivos de registro.
        /// </summary>
        internal static string LabelLogPath {
            get {
                return ResourceManager.GetString("LabelLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elija el tamaño máximo del archivo (en Kilobytes).
        /// </summary>
        internal static string LabelMaxFileSize {
            get {
                return ResourceManager.GetString("LabelMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de la copia de seguridad.
        /// </summary>
        internal static string LabelNameSave {
            get {
                return ResourceManager.GetString("LabelNameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tipo de copia de seguridad.
        /// </summary>
        internal static string LabelSaveType {
            get {
                return ResourceManager.GetString("LabelSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruta de origen del archivo.
        /// </summary>
        internal static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruta del archivo de destino.
        /// </summary>
        internal static string LabelTarget {
            get {
                return ResourceManager.GetString("LabelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elija la extensión del archivo de registro.
        /// </summary>
        internal static string LabelTypeExt {
            get {
                return ResourceManager.GetString("LabelTypeExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abrir el expediente.
        /// </summary>
        internal static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crear una nueva copia de seguridad.
        /// </summary>
        internal static string TextBoxCreateSave {
            get {
                return ResourceManager.GetString("TextBoxCreateSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modificar la copia de seguridad.
        /// </summary>
        internal static string TextBoxEditSave {
            get {
                return ResourceManager.GetString("TextBoxEditSave", resourceCulture);
            }
        }
    }
}
